### ISSUE TITLE
SimpleCommand dictionary key error upon quitting a game to main menu and reloading the saved game.

### ISSUE THREAD

**Issue by jakemaguy** [XarotDev/SimpleCommand.API#2]
### Other Mod's Im using
- LC_API `V3.3.2`
- BepInEx `V5.4.2100`
- TerminalGames `V1.2.0`
- Lethal Company `v49`

### Problem Details
I am using SimpleCommandAPI `V1.0.1`.  I noticed that when I quit the game and go back to the main menu then reload a save, there's some strange behavior:

- Can't hit escape
- When opening Terminal, my typing cursor is at the top of the screen, and I can't enter any commands

<p align="center">
<img src="https://github.com/XarotDev/SimpleCommand.API/assets/36657294/3fd370d6-9dd3-4ed6-b4b4-aa9e773801cc" width="60%" />
</p>
I'm unable to exit the terminal either and have no choice but to alt-tab and close the game.

### Error Message

```
[Error  : Unity Log] ArgumentException: An item with the same key has already been added. Key: [1, System.Collections.Generic.List`1[System.String]]
Stack trace:
System.Collections.Generic.TreeSet`1[T].AddIfNotPresent (T item) (at <d054a9182977441aa432503a474315ba>:0)
System.Collections.Generic.SortedSet`1[T].Add (T item) (at <d054a9182977441aa432503a474315ba>:0)
System.Collections.Generic.SortedDictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <d054a9182977441aa432503a474315ba>:0)
SimpleCommand.API.Patches.SimpleCommandPatches.PatchAwake (Terminal& __instance) (at <90d337873be242bea1ef0b5a70cc9a14>:0)
(wrapper dynamic-method) Terminal.DMD<Terminal::Awake>(Terminal)
```

### Possible Solution
In `SimpleCommand.API/Patches/SimpleCommand.Patches.cs` a potential solution for the problem is to verify the absence of the dictionary Key before inserting it.

```diff
--- a/SimpleCommand.API/Patches/SimpleCommand.Patches.cs
+++ b/SimpleCommand.API/Patches/SimpleCommand.Patches.cs
@@ -101,7 +101,8 @@ namespace SimpleCommand.API.Patches
                             lines.Add(fillLines);
                         }

-                        SimpleCommandDictionary.Add(pageNumber, lines);
+                        if (!SimpleCommandDictionary.ContainsKey(pageNumber))
+                            SimpleCommandDictionary.Add(pageNumber, lines);
                         lines = new()
                         {
                             command
@@ -119,7 +120,8 @@ namespace SimpleCommand.API.Patches
                         string fillLines = new('\n', distance);
                         lines.Add(fillLines);
                     }
-                    SimpleCommandDictionary.Add(pageNumber, lines);
+                    if (!SimpleCommandDictionary.ContainsKey(pageNumber))
+                        SimpleCommandDictionary.Add(pageNumber, lines);
                 }
                 else if (lines.Count == 0)
                 {
@@ -127,7 +129,8 @@ namespace SimpleCommand.API.Patches
                     string fillLines = new('\n', maxVisibleLines-2);
                     lines.Add(error);
                     lines.Add(fillLines);
-                    SimpleCommandDictionary.Add(pageNumber, lines);
+                    if (!SimpleCommandDictionary.ContainsKey(pageNumber))
+                        SimpleCommandDictionary.Add(pageNumber, lines);
                 }
             }
         }

```

**Comment by XarotDev** [comment]
Thank you for using my API and I am sorry for this inconvenience.
I completely forgot about the saves and save-reloads. I'll look into it and patch it asap.
Meanwhile, if there are any features that this plugin needs to have, please don't hesitate to contact me.

**Comment by XarotDev** [comment]
Patch is now live. Please update your files @jakemaguy and tell me if you still encounter those errors.

**Comment by jakemaguy** [comment]
I tested out `v1.0.2` of your API and it worked after reloading the save.  This issue is okay to close now. 

Thank you for looking at it.  I'm developing a terminal-based mod utilizing your API, and I've been looking for a terminal API that allows you to configure dynamic custom arguments.  So far yours is the only one that Ive come across that allows for such a thing.
